plugins {
    id "idea"
    id "eclipse"
    id "maven-publish"
    id "net.neoforged.moddev" version "2.0.74"
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

base {
    version = minecraft_version + '-' + create_version + '-' + mod_version
    group = mod_author + '.' + mod_id // http://maven.apache.org/guides/mini/guide-naming-conventions.html
    archivesName = mod_id + "-neoforge"
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        configureEach {
            systemProperty 'mixin.debug.verbose', 'true'
            systemProperty 'mixin.debug.export', 'true'
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', "mingle", '--all', '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }
}

sourceSets.main.resources {
    srcDirs += 'src/generated/resources'
    exclude '.cache'
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    maven { url = "https://mvn.devos.one/snapshots" } // Registrate
    maven { url = "https://maven.createmod.net" } // Ponder, Flywheel
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" } // NeoForge config api port, needed by ponder
    maven { url = "https://www.cursemaven.com" }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")
    implementation("dev.engine-room.flywheel:flywheel-neoforge-${flywheel_minecraft_version}:${flywheel_version}")
    implementation("net.createmod.ponder:Ponder-NeoForge-${ponder_minecraft_version}:${ponder_version}")
    implementation("com.simibubi.create:create-${create_minecraft_version}:${create_version}-${create_version_suffix}") { transitive = false }

    if (!Boolean.getBoolean('idea.sync.active')) {
        //annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            "create_version_range" : create_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_author             : mod_author,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     : mod_id,
                "Specification-Vendor"    : mod_author,
                "Specification-Version"   : mod_version,
                "Implementation-Title"    : project.jar.archiveBaseName,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : mod_author,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs": "createpickywheels.mixins.json"
        ])
    }
}

compileJava {
    options.compilerArgs = ['-Xdiags:verbose']
}