plugins {
    id("idea")
    id("eclipse")
    id("maven-publish")
    //id("net.kyori.blossom") version "2.1.0" // https://github.com/KyoriPowered/blossom
    //id("dev.ithundxr.silk") version "1.0.1" // https://github.com/ithundxr/silk
    id("net.neoforged.moddev") version "2.0.107" // https://projects.neoforged.net/neoforged/ModDevGradle
    id("me.modmuss50.mod-publish-plugin") version "0.8.4" // https://github.com/modmuss50/mod-publish-plugin
    id("org.jetbrains.gradle.plugin.idea-ext") version "1.1.8" // https://github.com/JetBrains/gradle-idea-ext-plugin
}

apply(from: "./gradle/java.gradle")

base {
    version = minecraft_version + '-' + create_version + '-' + mod_version
    group = mod_author + '.' + mod_id // http://maven.apache.org/guides/mini/guide-naming-conventions.html
    archivesName = mod_id + "-neoforge"
}

println("Java: ${System.getProperty("java.version")}, JVM: ${System.getProperty("java.vm.version")} (${System.getProperty("java.vendor")}), Arch: ${System.getProperty("os.arch")}")

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

neoForge {
    version = neo_version

    //accessTransformers = files('src/main/resources/META-INF/accesstransformer.cfg')

    if (parchment_version != "none") {
        parchment {
            minecraftVersion = parchment_minecraft_version == "same" ? minecraft_version : parchment_minecraft_version
            mappingsVersion = parchment_version
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            jvmArgument("-XX:+IgnoreUnrecognizedVMOptions")
            jvmArgument("-XX:+AllowEnhancedClassRedefinition")
            //jvmArgument("-XX:-OmitStackTraceInFastThrow") // uncomment when you get exceptions with null messages etc
            //jvmArgument("-XX:+UnlockCommercialFeatures") // uncomment for profiling

            systemProperty("mixin.debug.verbose", "true")
            systemProperty("mixin.debug.export", "true")

            systemProperty("neoforge.enabledGameTestNamespaces", mod_id as String)
        }

        client {
            client()
        }

        server {
            server()
            gameDirectory = project.file("run/server")
            programArgument("--nogui")
        }

        data {
            data()
            programArguments.addAll(
                    '--mod', mod_id as String,
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath(),
                    '--existing-mod', 'create'
            )
        }

        gameTestServer {
            type = "gameTestServer"
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
    maven { url = "https://maven.createmod.net" } // Ponder, Flywheel
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" } // NeoForge config api port, needed by ponder
    maven { url = "https://www.cursemaven.com" }
}

dependencies {
    //implementation "net.neoforged:neoforge:${neo_version}"
    
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")
    implementation("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}-${create_version_suffix}:slim") { transitive = false }
}

sourceSets.main.resources {
    srcDirs += 'src/generated/resources'
    exclude '.cache'
}

jar {
    String name = base.archivesName.get()

    from("LICENSE") {
        rename { "${it}_$name" }
    }

    manifest.attributes([
            "MixinConfigs": "createpickywheels.mixins.json"
    ])
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            "mod_version"           : mod_version,
            "mod_id"                : mod_id,
            "mod_name"              : mod_name,
            "mod_author"            : mod_author,
            "mod_description"       : mod_description,
            "mod_license"           : mod_license,
            "neo_version"           : neo_version,
            "minecraft_version"     : minecraft_version,
            "create_version_range"  : create_version_range
    ]
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir(generateModMetadata)
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask(generateModMetadata)
