modLoader="javafml"
license="MIT"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/zehmaria/createpickywheels/issues"
displayURL="https://github.com/zehmaria/createpickywheels"
logoFile= "logo.png"

[[mods]]
    modId="createpickywheels"
    version="${file.jarVersion}"
    displayName="Create Picky Wheels"
	authors="zeh_maria"
    description="Changing Waterwheels generation requirements: Large body of water + River Biomes."

[[dependencies.createpickywheels]]
    modId="forge"
    mandatory=true
    ordering="NONE"
    versionRange="[40.2.0,)"
    side="BOTH"
[[dependencies.createpickywheels]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.a,0.5.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createpickywheels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
